import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import * as SecureStore from 'expo-secure-store';

const LanguageContext = createContext(null);
const LANGUAGE_KEY = 'rwanda_fda_language';

const DICT = {
  en: {
    tabHome: 'Home',
    tabTasks: 'Tasks',
    tabApps: 'Apps',
    tabAlerts: 'Alerts',
    tabYou: 'You',
    tabDashboardTitle: 'Dashboard',
    tabTasksTitle: 'My Tasks',
    tabApplicationsTitle: 'Applications',
    tabNotificationsTitle: 'Notifications',
    tabProfileTitle: 'My Profile',
    dashboardKicker: 'Rwanda FDA · Staff workspace',
    dashboardHi: 'Hi',
    dashboardTaglineWithStation: '{station} — applications, tasks, and alerts in one place.',
    dashboardTaglineDefault: 'Your monitoring hub for applications, tasks, and team alerts.',
    overview: 'Overview',
    applications: 'Applications',
    assignments: 'Assignments',
    inProgress: 'In progress',
    needsAttention: 'Needs attention',
    behindSchedule: 'Behind schedule',
    tasks: 'Tasks',
    stillOpen: 'Still open',
    allDone: 'All done',
    completed: 'Completed',
    dueSoon: 'Due soon',
    reports: 'Reports',
    applicationsWorkingOn: 'Applications you are working on',
    assignmentsWord: 'assignments',
    activeWord: 'active',
    delayedWord: 'delayed',
    atRiskWord: 'at risk',
    totalAssignments: 'Total assignments',
    uniqueFilings: 'Unique filings',
    openFullReport: 'Open full report',
    yourWorkloadDeadlines: 'Your workload and deadlines',
    openWord: 'open',
    doneWord: 'done',
    tasksWord: 'tasks',
    dueSoonWord: 'due soon',
    completionRate: 'Completion rate',
    totalTracked: 'Total tracked',
    updatedAt: 'Updated',
    yourTasks: 'Your tasks',
    openWorkAssigned: 'Open work assigned to you',
    seeAll: 'See all',
    noTasksAssigned: 'No tasks assigned - check back later or open Tasks for the full list.',
    noOpenTasks: 'No open tasks - you are all caught up.',
    duePrefix: 'Due',
    noDueDate: 'No due date',
    appsTapRow: 'Tap a row for more',
    fullList: 'Full list',
    refShort: 'Ref',
    status: 'Status',
    daysLeft: 'Days left',
    noApplicationRecords: 'No application records available.',
    stage: 'Stage',
    daysUsed: 'Days used',
    assigned: 'Assigned',
    topNotifications: 'Top notifications',
    retry: 'Retry',
    settings: 'Settings',
    settingsSub: 'Control alerts, meetings and app preferences.',
    appearance: 'Appearance',
    appearanceSub: 'Choose Light, Dark, or follow your device setting.',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    profileSection: 'Profile',
    profileSectionSub: 'Account and support features.',
    profileInformation: 'Profile information',
    profileInformationSub: 'View your profile, organization and hierarchy.',
    securityAccess: 'Security & Access',
    securityAccessSub: 'Passcode, biometrics and login details.',
    helpSupport: 'Help & Support',
    notifications: 'Notifications',
    notificationsSub: 'These are local preferences. API integration will come later.',
    taskUpdates: 'Task updates',
    taskUpdatesSub: 'Alerts when tasks change status or are close to due.',
    applicationUpdates: 'Application updates',
    applicationUpdatesSub: 'Notifications for submissions, approvals and holds.',
    meetingReminders: 'Meeting reminders',
    meetingRemindersSub: 'Prepare for upcoming review and coordination meetings.',
    appSettings: 'App settings',
    more: 'More',
    logout: 'Logout',
    logoutSub: 'Sign out from this device.',
    rateUs: 'Rate us',
    rateUsSub: 'Share your feedback on the app store.',
    inviteFriend: 'Invite a friend',
    inviteFriendSub: 'Share the app with your team.',
    dataPolicy: 'Data collection policy',
    dataPolicySub: 'Read privacy and policy details.',
    language: 'Language',
    english: 'English',
    french: 'Francais',
    shareWithFriends: 'Share with friends',
    shareSub: 'Spread the word and empower your team to manage applications and tasks seamlessly.',
    shareCta: 'Share Rwanda FDA App',
    profile: 'Profile',
    rfdaStaff: 'RFDA Staff',
    staffMember: 'Staff member',
    noWorkEmail: 'No work email',
    openTasks: 'Open tasks',
    unread: 'Unread',
    myDetails: 'My details',
    verified: 'Verified',
    workEmail: 'Work email',
    phone: 'Phone',
    dutyStation: 'Duty station',
    staffGroup: 'Staff group',
    position: 'Position',
    organization: 'Organization',
    more: 'More',
    degree: 'Degree',
    qualifications: 'Qualifications',
    contract: 'Contract',
    hireDate: 'Hire date',
    mySnapshot: 'My snapshot',
    completedTasks: 'Completed tasks',
    applicationsQueue: 'Applications in my queue',
    unreadNotifications: 'Unread notifications',
    staffHierarchy: 'Staff hierarchy',
    reportOne: 'report',
    reportMany: 'reports',
    reportsTo: 'Reports To',
    noManagerFound: 'No manager found.',
    directReports: 'Direct reports',
    noDirectReports: 'No staff currently reporting to you.',
    noDirectReportsFiltered: 'No direct reports match Under Statute with active status.',
    loadMoreLeft: 'Load more ({left} left)',
    secSub: 'Manage sign-in and account protection settings.',
    accessDetails: 'Access details',
    changePassword: 'Change password',
    changePasswordSub: 'Reset your account password.',
    secPreferences: 'Security preferences',
    useBiometrics: 'Use biometrics',
    useBiometricsSub: 'Login with face or fingerprint recognition.',
    rememberDevice: 'Remember this device',
    rememberDeviceSub: 'Keep your session active on this phone.',
    all: 'All',
    open: 'Open',
    notStarted: 'Not started',
    active: 'Active',
    inReview: 'In review',
    done: 'Done',
    late: 'Late',
    myTasks: 'My tasks',
    tapTaskToOpen: 'Tap a task to open details and timeline',
    searchTasks: 'Search tasks',
    task: 'Task',
    inThisList: 'in this list',
    noTasksMatch: 'No tasks match',
    tryAnotherFilter: 'Try another status filter or clear the search.',
    timeline: 'Timeline',
    untitledTask: 'Untitled task',
    noDescription: 'No description',
    deadline: 'Deadline',
    slaWindow: 'SLA window',
    remaining: 'remaining',
    application: 'Application',
    openDetails: 'Open details',
    uniqueApps: 'Unique apps',
    onTime: 'On time',
    atRisk: 'At risk',
    delayed: 'Delayed',
    left: 'left',
    progress: 'Progress',
    assignment: 'Assignment',
    submitted: 'Submitted',
    attention: 'Attention',
    unique: 'Unique',
    searchReferenceApplicantStage: 'Search reference, applicant, stage...',
    noApplicationsYet: 'No applications yet',
    applicationsAppearHere: 'When assignments are linked to your account, they will appear here.',
    noMatches: 'No matches',
    noMatchesTryFilter: 'Try another filter or clear the search.',
    resetFilters: 'Reset filters',
    updates: 'Updates',
    today: 'Today',
    yesterday: 'Yesterday',
    justNow: 'Just now',
    update: 'Update',
    noAdditionalDetails: 'No additional details.',
    new: 'New',
    read: 'Read',
    inbox: 'Inbox',
    pullToRefresh: 'pull to refresh',
    allCaughtUp: 'You are all caught up',
    updatesFromRfda: 'Updates from Rwanda FDA',
    searchNotifications: 'Search notifications...',
    nothingHereYet: 'Nothing here yet',
    notificationsEmpty: 'New task and application updates will show up here.',
    sessionExpired: 'Session expired',
    somethingWentWrong: 'Something went wrong',
    signOutAndSignInAgain: 'Sign out and sign in again',
    couldNotLoadNotifications: "Couldn't load notifications",
    workingOn: 'Working on it',
  },
  fr: {
    tabHome: 'Accueil',
    tabTasks: 'Taches',
    tabApps: 'Apps',
    tabAlerts: 'Alertes',
    tabYou: 'Profil',
    tabDashboardTitle: 'Tableau de bord',
    tabTasksTitle: 'Mes taches',
    tabApplicationsTitle: 'Applications',
    tabNotificationsTitle: 'Notifications',
    tabProfileTitle: 'Mon profil',
    dashboardKicker: 'Rwanda FDA · Espace staff',
    dashboardHi: 'Salut',
    dashboardTaglineWithStation: '{station} — applications, taches et alertes au meme endroit.',
    dashboardTaglineDefault: 'Votre hub pour applications, taches et alertes equipe.',
    overview: "Vue d'ensemble",
    applications: 'Applications',
    assignments: 'Affectations',
    inProgress: 'En cours',
    needsAttention: 'A surveiller',
    behindSchedule: 'En retard',
    tasks: 'Taches',
    stillOpen: 'Encore ouvertes',
    allDone: 'Tout termine',
    completed: 'Terminees',
    dueSoon: 'Bientot echeance',
    reports: 'Rapports',
    applicationsWorkingOn: 'Applications en cours',
    assignmentsWord: 'affectations',
    activeWord: 'actives',
    delayedWord: 'retardees',
    atRiskWord: 'a risque',
    totalAssignments: 'Total des affectations',
    uniqueFilings: 'Dossiers uniques',
    openFullReport: 'Ouvrir le rapport complet',
    yourWorkloadDeadlines: 'Votre charge de travail et vos echeances',
    openWord: 'ouvertes',
    doneWord: 'termine',
    tasksWord: 'taches',
    dueSoonWord: 'bientot echeance',
    completionRate: 'Taux de completion',
    totalTracked: 'Total suivi',
    updatedAt: 'Mis a jour',
    yourTasks: 'Vos taches',
    openWorkAssigned: 'Travail ouvert qui vous est assigne',
    seeAll: 'Voir tout',
    noTasksAssigned: "Aucune tache assignee - revenez plus tard ou ouvrez Taches pour la liste complete.",
    noOpenTasks: 'Aucune tache ouverte - tout est a jour.',
    duePrefix: 'Echeance',
    noDueDate: "Pas de date d'echeance",
    appsTapRow: 'Touchez une ligne pour plus de details',
    fullList: 'Liste complete',
    refShort: 'Ref',
    status: 'Statut',
    daysLeft: 'Jours restants',
    noApplicationRecords: "Aucun enregistrement d'application disponible.",
    stage: 'Etape',
    daysUsed: 'Jours utilises',
    assigned: 'Assigne',
    topNotifications: 'Principales notifications',
    retry: 'Reessayer',
    settings: 'Parametres',
    settingsSub: "Controlez les alertes, reunions et preferences de l'application.",
    appearance: 'Apparence',
    appearanceSub: 'Choisissez Clair, Sombre ou le mode systeme.',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Systeme',
    profileSection: 'Profil',
    profileSectionSub: 'Compte et assistance.',
    profileInformation: 'Informations du profil',
    profileInformationSub: 'Voir votre profil, organisation et hierarchie.',
    securityAccess: 'Securite et acces',
    securityAccessSub: "Code, biometrie et details de connexion.",
    helpSupport: 'Aide et support',
    notifications: 'Notifications',
    notificationsSub: "Preferences locales. L'integration API viendra plus tard.",
    taskUpdates: 'Mises a jour des taches',
    taskUpdatesSub: 'Alertes sur les changements et echeances des taches.',
    applicationUpdates: 'Mises a jour des applications',
    applicationUpdatesSub: 'Notifications pour soumissions, approbations et mises en attente.',
    meetingReminders: 'Rappels de reunions',
    meetingRemindersSub: 'Preparez les reunions de revue et coordination.',
    appSettings: "Parametres de l'application",
    more: 'Plus',
    logout: 'Deconnexion',
    logoutSub: 'Se deconnecter de cet appareil.',
    rateUs: 'Notez-nous',
    rateUsSub: "Partagez votre avis sur l'App Store.",
    inviteFriend: 'Inviter un ami',
    inviteFriendSub: "Partagez l'application avec votre equipe.",
    dataPolicy: 'Politique de donnees',
    dataPolicySub: 'Lire les details de confidentialite.',
    language: 'Langue',
    english: 'Anglais',
    french: 'Francais',
    shareWithFriends: 'Partager avec des amis',
    shareSub: "Faites connaitre l'application pour gerer les dossiers et taches facilement.",
    shareCta: "Partager l'application Rwanda FDA",
    profile: 'Profil',
    rfdaStaff: 'Agent RFDA',
    staffMember: 'Membre du personnel',
    noWorkEmail: "Pas d'email professionnel",
    openTasks: 'Taches ouvertes',
    unread: 'Non lues',
    myDetails: 'Mes details',
    verified: 'Verifie',
    workEmail: 'Email professionnel',
    phone: 'Telephone',
    dutyStation: 'Poste',
    staffGroup: 'Groupe du personnel',
    position: 'Poste',
    organization: 'Organisation',
    more: 'Plus',
    degree: 'Diplome',
    qualifications: 'Qualifications',
    contract: 'Contrat',
    hireDate: "Date d'embauche",
    mySnapshot: 'Mon resume',
    completedTasks: 'Taches terminees',
    applicationsQueue: "Applications dans ma file",
    unreadNotifications: 'Notifications non lues',
    staffHierarchy: 'Hierarchie du personnel',
    reportOne: 'rapport',
    reportMany: 'rapports',
    reportsTo: 'Superviseur',
    noManagerFound: 'Aucun manager trouve.',
    directReports: 'Rapports directs',
    noDirectReports: 'Aucun agent ne vous rapporte actuellement.',
    noDirectReportsFiltered: "Aucun rapport direct ne correspond au filtre.",
    loadMoreLeft: 'Charger plus ({left} restants)',
    secSub: 'Gerez la connexion et la protection du compte.',
    accessDetails: "Details d'acces",
    changePassword: 'Changer le mot de passe',
    changePasswordSub: 'Reinitialiser le mot de passe du compte.',
    secPreferences: 'Preferences de securite',
    useBiometrics: 'Utiliser la biometrie',
    useBiometricsSub: 'Connexion avec visage ou empreinte digitale.',
    rememberDevice: 'Se souvenir de cet appareil',
    rememberDeviceSub: 'Conserver votre session active sur ce telephone.',
    all: 'Tout',
    open: 'Ouvert',
    notStarted: 'Non commence',
    active: 'Actif',
    inReview: 'En revue',
    done: 'Termine',
    late: 'En retard',
    myTasks: 'Mes taches',
    tapTaskToOpen: 'Touchez une tache pour ouvrir les details et la timeline',
    searchTasks: 'Rechercher des taches',
    task: 'Tache',
    inThisList: 'dans cette liste',
    noTasksMatch: 'Aucune tache correspondante',
    tryAnotherFilter: 'Essayez un autre filtre ou effacez la recherche.',
    timeline: 'Timeline',
    untitledTask: 'Tache sans titre',
    noDescription: 'Aucune description',
    deadline: 'Echeance',
    slaWindow: 'Fenetre SLA',
    remaining: 'restants',
    application: 'Application',
    openDetails: 'Ouvrir les details',
    uniqueApps: 'Apps uniques',
    onTime: 'A temps',
    atRisk: 'A risque',
    delayed: 'Retarde',
    left: 'restants',
    progress: 'Progression',
    assignment: 'Affectation',
    submitted: 'Soumis',
    attention: 'Attention',
    unique: 'Unique',
    searchReferenceApplicantStage: 'Rechercher reference, demandeur, etape...',
    noApplicationsYet: 'Aucune application pour le moment',
    applicationsAppearHere: 'Les affectations liees a votre compte apparaitront ici.',
    noMatches: 'Aucun resultat',
    noMatchesTryFilter: 'Essayez un autre filtre ou effacez la recherche.',
    resetFilters: 'Reinitialiser les filtres',
    updates: 'Mises a jour',
    today: "Aujourd'hui",
    yesterday: 'Hier',
    justNow: "A l'instant",
    update: 'Mise a jour',
    noAdditionalDetails: 'Aucun detail supplementaire.',
    new: 'Nouveau',
    read: 'Lu',
    inbox: 'Boite de reception',
    pullToRefresh: 'glissez pour actualiser',
    allCaughtUp: 'Tout est a jour',
    updatesFromRfda: 'Mises a jour de Rwanda FDA',
    searchNotifications: 'Rechercher des notifications...',
    nothingHereYet: 'Rien ici pour le moment',
    notificationsEmpty: "Les nouvelles mises a jour de taches et d'applications apparaitront ici.",
    sessionExpired: 'Session expiree',
    somethingWentWrong: "Une erreur s'est produite",
    signOutAndSignInAgain: 'Deconnectez-vous puis reconnectez-vous',
    couldNotLoadNotifications: 'Impossible de charger les notifications',
    workingOn: 'Personne en charge',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const stored = await SecureStore.getItemAsync(LANGUAGE_KEY);
        if (stored === 'en' || stored === 'fr') setLanguageState(stored);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const setLanguage = async (next) => {
    const value = next === 'fr' ? 'fr' : 'en';
    setLanguageState(value);
    await SecureStore.setItemAsync(LANGUAGE_KEY, value).catch(() => {});
  };

  const t = (key) => DICT[language]?.[key] ?? DICT.en[key] ?? key;

  const value = useMemo(
    () => ({ language, setLanguage, t, loading }),
    [language, loading]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return { language: 'en', setLanguage: async () => {}, t: (key) => DICT.en[key] ?? key, loading: false };
  }
  return ctx;
}
